// decode_helper.js
// 从 stdin 读取加密字符串，输出解密后的图片URL列表（JSON数组）
// 用法: echo "encrypted_string" | node decode_helper.js
// 或者: node decode_helper.js "encrypted_string"
//
// Generated by Trae (https://trae.ai)

'use strict';

const DECODER_URL = 'https://m.baozimh.org/assets/runtime/chapter-decoder.js';

// ============ 设置浏览器模拟环境 ============
const noop = () => {};
const noopFn = function() { return ''; };

// 反调试代码会调用 console.xxx.toString()，需要让它返回特定格式的字符串
function makeFakeConsole() {
  const methods = ['log', 'warn', 'error', 'debug', 'info', 'exception', 'table', 'trace'];
  const fake = {};
  for (const m of methods) {
    const fn = function() {};
    fn.toString = function() { return 'function ' + m + '() { [native code] }'; };
    fn.toSource = noopFn;
    fake[m] = fn;
  }
  return fake;
}

// 安装到 global
global.window = global;
global.self = global;
global.top = global;
global.parent = global;
global.document = {
  createElement: () => ({ setAttribute: noop, style: {}, appendChild: noop, removeChild: noop }),
  createTextNode: () => ({}),
  getElementsByTagName: () => [],
  querySelector: () => null,
  querySelectorAll: () => [],
  addEventListener: noop,
  removeEventListener: noop,
  documentElement: { style: {} },
  head: { appendChild: noop },
  body: { appendChild: noop },
  title: '',
};
try {
  Object.defineProperty(global, 'navigator', {
    value: {
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
    },
    writable: true,
    configurable: true,
    enumerable: true,
  });
} catch(e) {}

try {
  Object.defineProperty(global, 'location', {
    value: {
      hostname: 'm.baozimh.org',
      href: 'https://m.baozimh.org/',
      protocol: 'https:',
      host: 'm.baozimh.org',
      pathname: '/',
      search: '',
      hash: '',
    },
    writable: true,
    configurable: true,
    enumerable: true,
  });
} catch(e) {}
global.__img = {};
global.__cimg = {};

// 覆盖 console 防止反调试干扰
const fakeConsole = makeFakeConsole();
for (const key of Object.keys(fakeConsole)) {
  console[key] = fakeConsole[key];
}

// ============ 读取输入 ============
function readStdin() {
  return new Promise((resolve, reject) => {
    let data = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (chunk) => data += chunk);
    process.stdin.on('end', () => resolve(data));
    process.stdin.on('error', reject);
    setTimeout(() => resolve(data), 5000);
  });
}

async function main() {
  const input = process.argv[2] || (await readStdin());
  if (!input || !input.trim()) {
    process.stderr.write('ERROR: 未提供加密字符串\n');
    process.exit(1);
  }

  let code;
  try {
    const resp = await fetch(DECODER_URL);
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    code = await resp.text();
  } catch (err) {
    process.stderr.write('ERROR: 下载解密器失败: ' + err.message + '\n');
    process.exit(1);
  }

  try {
    // 使用 indirect eval 在全局作用域执行解密器代码
    const evalGlobal = eval;
    evalGlobal(code);

    // 检查解密函数是否已注册
    const decoder = global.__img.fromCode;
    if (typeof decoder !== 'function') {
      const decoder2 = global.__cimg && global.__cimg.r;
      if (typeof decoder2 !== 'function') {
        throw new Error('未找到解密函数 (window.__img.fromCode 或 window.__cimg.r)');
      }
    }

    const fn = decoder || global.__cimg.r;
    const result = await fn(input.trim());

    // 输出JSON数组
    if (Array.isArray(result)) {
      process.stdout.write(JSON.stringify(result) + '\n');
    } else {
      process.stdout.write(JSON.stringify([result]) + '\n');
    }
  } catch (err) {
    process.stderr.write('ERROR: 解密失败: ' + err.message + '\n');
    process.exit(1);
  }
}

main();