#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
baozimh-downloader: 包子漫画(baozimh.org) 通用下载器
从 m.baozimh.org 下载任意漫画全部章节，按章节和页数顺序存放。

依赖: Python 3.7+, requests, Node.js 18+ (用于图片URL解密)

用法:
  python download.py <漫画slug>                      # 下载到当前目录
  python download.py <漫画slug> -o D:/comics         # 下载到指定目录
  python download.py <漫画slug> --start 5 --end 10   # 只下载第5-10话
  python download.py <漫画slug> --list               # 只列出章节，不下载

示例:
  python download.py fannaoxiyouji
  python download.py one-piece -o D:/海贼王
  python download.py fannaoxiyouji --start 1 --end 3

特性:
  - 通用: 支持包子漫画上任意漫画
  - 断点续传: 已下载的章节自动跳过，中断后重新运行即可继续
  - 多CDN回退: 自动尝试多个CDN节点
  - 选话下载: 支持 --start/--end 指定章节范围
  - 图片URL解密: 通过Node.js执行原始解密器，自动适配网站更新

Generated by Trae (https://trae.ai)
"""

import argparse
import json
import re
import subprocess
import sys
import time
from pathlib import Path

import requests

# ==================== 站点配置 ====================
SITE_HOST = "https://m.baozimh.org"
CHAPTER_LIST_API = "https://v2.apikk.top/api/manga/get"
CHAPTER_INFO_API = "https://v2.apikk.top/api/v2/chapter/getinfo"
CDN_BASES = [
    "https://c-nd3-1.6wm.top",
    "https://c-nd2-1.6wm.top",
    "https://t-nd3-1.6wm.top",
    "https://t-nd2-1.6wm.top",
]

# 下载设置
MAX_RETRIES = 3
RETRY_DELAY = 2
REQUEST_TIMEOUT = 30
DOWNLOAD_TIMEOUT = 60
CHAPTER_DELAY = 1  # 章节间延迟(秒)

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Accept": "application/json, text/plain, */*",
    "Origin": SITE_HOST,
    "Referer": SITE_HOST + "/",
}

session = requests.Session()
session.headers.update(HEADERS)


# ==================== 网络请求 ====================

def get_manga_id(slug):
    """从章节列表页提取漫画ID"""
    url = f"{SITE_HOST}/chapterlist/{slug}"
    resp = session.get(url, timeout=REQUEST_TIMEOUT)
    resp.raise_for_status()
    match = re.search(r'data-mid="(\d+)"', resp.text)
    if not match:
        raise ValueError(f"无法从页面中提取漫画ID，请检查slug是否正确: {slug}")
    return match.group(1)


def get_manga_info(mid):
    """通过API获取漫画标题和章节列表"""
    print(f"正在获取漫画信息 (mid={mid})...")
    resp = session.get(CHAPTER_LIST_API, params={"mid": mid, "mode": "all"},
                       timeout=REQUEST_TIMEOUT)
    resp.raise_for_status()
    data = resp.json()
    if data.get("code") != 200:
        raise ValueError(f"API返回错误: {data}")
    info = data["data"]
    manga_title = info.get("title", "")
    chapters = info["chapters"]
    print(f"漫画: {manga_title}")
    print(f"共找到 {len(chapters)} 话")
    return manga_title, chapters


def get_chapter_images(mid, chapter_id):
    """获取章节的加密图片数据"""
    resp = session.get(
        CHAPTER_INFO_API,
        params={"m": mid, "c": chapter_id},
        timeout=REQUEST_TIMEOUT
    )
    resp.raise_for_status()
    data = resp.json()
    if data.get("code") != 200:
        raise ValueError(f"获取章节信息失败: {data}")
    info = data["data"]["info"]
    encrypted_images = info["images"]["images"]
    title = info.get("title", "").strip()
    return encrypted_images, title


# ==================== 解密 ====================

def decode_image_urls(encrypted_string):
    """调用Node.js解密图片URL列表"""
    decoder_path = Path(__file__).parent / "decode_helper.js"
    if not decoder_path.exists():
        raise FileNotFoundError(
            f"找不到解密辅助脚本: {decoder_path}\n"
            f"请确保 decode_helper.js 与 download.py 在同一目录下"
        )

    result = subprocess.run(
        ["node", str(decoder_path)],
        input=encrypted_string,
        capture_output=True,
        text=True,
        timeout=30,
        encoding="utf-8",
    )

    if result.returncode != 0:
        raise RuntimeError(f"解密失败: {result.stderr.strip()}")

    output = result.stdout.strip()
    if not output:
        raise ValueError("解密结果为空")

    try:
        items = json.loads(output)
    except json.JSONDecodeError:
        urls = [line.strip() for line in output.split("\n") if line.strip()]
        return urls

    items.sort(key=lambda x: x.get("order", 0))
    urls = [item["url"] for item in items if "url" in item]
    if not urls:
        raise ValueError("解密结果中无有效URL")
    return urls


# ==================== 下载 ====================

def sanitize_filename(name, max_length=80):
    """清理文件名，移除非法字符"""
    name = re.sub(r'[<>:"/\\|?*]', '_', name)
    name = name.strip(' .')
    if len(name) > max_length:
        name = name[:max_length].rstrip(' .')
    return name or "unnamed"


def guess_extension(url, content_type):
    """根据URL和Content-Type猜测文件扩展名"""
    url_lower = url.split("?")[0].lower()
    for ext in [".webp", ".jpg", ".jpeg", ".png", ".gif"]:
        if ext in url_lower:
            return ext
    ct = content_type.lower()
    for keyword, ext in [("webp", ".webp"), ("jpeg", ".jpg"), ("jpg", ".jpg"),
                          ("png", ".png"), ("gif", ".gif")]:
        if keyword in ct:
            return ext
    return ".jpg"


def download_image(url, save_path, retries=MAX_RETRIES):
    """下载单张图片，支持多CDN回退"""
    if url.startswith("/"):
        url_path = url
    elif url.startswith("http"):
        rest = url.split("://", 1)[1]
        url_path = rest.split("/", 1)[1] if "/" in rest else "/" + rest
    else:
        url_path = "/" + url

    for attempt in range(1, retries + 1):
        for cdn in CDN_BASES:
            full_url = cdn + url_path
            try:
                resp = session.get(full_url, timeout=DOWNLOAD_TIMEOUT, stream=True)
                if resp.status_code == 404:
                    continue
                resp.raise_for_status()

                content_type = resp.headers.get("Content-Type", "")
                if "image" not in content_type and "octet-stream" not in content_type:
                    continue

                ext = guess_extension(url_path, content_type)
                if not save_path.suffix or save_path.suffix.lower() == '.tmp':
                    save_path = save_path.with_suffix(ext)

                save_path.parent.mkdir(parents=True, exist_ok=True)
                with open(save_path, "wb") as f:
                    for chunk in resp.iter_content(chunk_size=8192):
                        f.write(chunk)

                file_size = save_path.stat().st_size
                if file_size < 1024:
                    save_path.unlink()
                    raise ValueError(f"文件过小 ({file_size} bytes)")

                return save_path, file_size

            except requests.exceptions.HTTPError:
                continue
            except Exception:
                if attempt < retries:
                    break
                raise

        if attempt < retries:
            print(f"  重试 ({attempt}/{retries}): 所有CDN均失败")
            time.sleep(RETRY_DELAY * attempt)

    raise RuntimeError(f"所有CDN均无法下载: {url_path}")


def download_chapter(mid, chapter, output_dir, chapter_index, total_chapters, skip_existing=True):
    """下载单个章节的全部图片"""
    chapter_id = chapter["id"]
    attrs = chapter["attributes"]
    title = attrs.get("title", f"第{attrs.get('order', chapter_index)}话")
    order = attrs.get("order", chapter_index)

    folder_name = sanitize_filename(f"{order:03d}_{title}")
    chapter_dir = output_dir / folder_name

    print(f"\n[{chapter_index}/{total_chapters}] {title} (id={chapter_id})")

    # 断点续传
    if skip_existing and chapter_dir.exists() and any(chapter_dir.iterdir()):
        existing = list(chapter_dir.iterdir())
        print(f"  已存在 {len(existing)} 个文件，跳过")
        return True

    try:
        encrypted_images, _ = get_chapter_images(mid, chapter_id)
    except Exception as e:
        print(f"  获取章节信息失败: {e}")
        return False

    try:
        image_urls = decode_image_urls(encrypted_images)
    except Exception as e:
        print(f"  解密图片URL失败: {e}")
        return False

    print(f"  共 {len(image_urls)} 页")

    success_count = 0
    fail_count = 0

    for i, url in enumerate(image_urls, 1):
        save_path = chapter_dir / f"{i:03d}"
        try:
            final_path, size = download_image(url, save_path)
            success_count += 1
            print(f"  [{i}/{len(image_urls)}] {final_path.name} ({size / 1024:.0f}KB)")
        except Exception as e:
            fail_count += 1
            print(f"  [{i}/{len(image_urls)}] 下载失败: {e}")

    print(f"  完成: {success_count} 成功, {fail_count} 失败")
    return fail_count == 0


# ==================== CLI ====================

def check_nodejs():
    """检查Node.js是否可用"""
    try:
        result = subprocess.run(["node", "--version"], capture_output=True,
                                text=True, timeout=5)
        version = result.stdout.strip()
        # 检查大版本 >= 18 (fetch API支持)
        major = int(re.search(r'v(\d+)', version).group(1))
        if major < 18:
            print(f"警告: Node.js {version}，建议 18+ 以支持内置fetch")
        return version
    except FileNotFoundError:
        return None
    except (subprocess.TimeoutExpired, AttributeError):
        return None


def parse_args():
    parser = argparse.ArgumentParser(
        description="包子漫画(baozimh.org)通用下载器",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  %(prog)s fannaoxiyouji                    下载"烦恼西游记"到当前目录
  %(prog)s fannaoxiyouji -o D:\\comics      下载到指定目录
  %(prog)s fannaoxiyouji --start 5 --end 10 只下载第5-10话
  %(prog)s fannaoxiyouji --list             只列出章节不下载

漫画slug即URL中的标识符，例如:
  https://m.baozimh.org/chapterlist/fannaoxiyouji
                                        ^^^^^^^^^^^^^^ 即为slug
        """,
    )
    parser.add_argument("slug", help="漫画slug (如 fannaoxiyouji)")
    parser.add_argument("-o", "--output", default=None,
                        help="保存目录 (默认: ./<漫画标题>)")
    parser.add_argument("--start", type=int, default=None,
                        help="起始章节号 (从1开始)")
    parser.add_argument("--end", type=int, default=None,
                        help="结束章节号 (含)")
    parser.add_argument("--list", action="store_true",
                        help="只列出章节，不下载")
    parser.add_argument("--no-skip", action="store_true",
                        help="不跳过已下载的章节 (默认跳过)")
    return parser.parse_args()


def main():
    args = parse_args()
    slug = args.slug.strip("/")

    print(f"包子漫画下载器")
    print(f"目标: {slug}")
    print("=" * 50)

    # 检查Node.js
    node_version = check_nodejs()
    if not node_version:
        print("错误: 未找到 Node.js")
        print("图片URL解密需要 Node.js 18+ (内置fetch支持)")
        print("请安装: https://nodejs.org/")
        sys.exit(1)
    print(f"Node.js: {node_version}")

    # 1. 获取漫画ID
    try:
        mid = get_manga_id(slug)
        print(f"漫画ID: {mid}")
    except Exception as e:
        print(f"获取漫画信息失败: {e}")
        sys.exit(1)

    # 2. 获取章节列表和标题
    try:
        manga_title, chapters = get_manga_info(mid)
    except Exception as e:
        print(f"获取章节列表失败: {e}")
        sys.exit(1)

    if not chapters:
        print("章节列表为空")
        sys.exit(0)

    # 3. 应用章节范围过滤
    if args.start or args.end:
        start = args.start or 1
        end = args.end or len(chapters)
        chapters = chapters[start - 1:end]
        print(f"筛选范围: 第{start}话 - 第{end}话 (共{len(chapters)}话)")

    # 4. 列表模式
    if args.list:
        print(f"\n{'序号':>4}  {'章节ID':>10}  标题")
        print("-" * 50)
        for i, ch in enumerate(chapters, 1):
            attrs = ch["attributes"]
            title = attrs.get("title", "").strip()
            order = attrs.get("order", i)
            print(f"{i:>4}  {ch['id']:>10}  {title}")
        return

    # 5. 确定输出目录
    if args.output:
        output_dir = Path(args.output)
    else:
        output_dir = Path.cwd() / sanitize_filename(manga_title)
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"保存目录: {output_dir}")

    # 6. 逐章下载
    total = len(chapters)
    success_chapters = 0
    fail_chapters = 0

    skip_existing = not args.no_skip

    for i, chapter in enumerate(chapters, 1):
        ok = download_chapter(mid, chapter, output_dir, i, total, skip_existing=skip_existing)
        if ok:
            success_chapters += 1
        else:
            fail_chapters += 1
        if i < total:
            time.sleep(CHAPTER_DELAY)

    # 7. 汇总
    print("\n" + "=" * 50)
    print(f"下载完成!")
    print(f"  漫画: {manga_title}")
    print(f"  成功: {success_chapters}/{total} 话")
    if fail_chapters > 0:
        print(f"  失败: {fail_chapters}/{total} 话 (重新运行即可续传，已下载章节自动跳过)")
    print(f"  保存位置: {output_dir}")


if __name__ == "__main__":
    main()